/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AddressBook;

// import org.junit.Test;
// // import static org.junit.Assert.*;

// public class AppTest {
//     @Test 
//     public void testAppHasAGreeting() {
//          AddressBook classUnderTest = new AddressBook();
//         // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//     }
// }
